language: node_js
node_js: stable

install:
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "propersoft-ci"
  - git config user.email "hexin@propersoft.cn"
  - git add .
  - git commit -m "Update docs"
<<<<<<< HEAD
  - git push --force "https://$GH_TOKEN@$GH_REF" master:master
=======
  - git push --force "https://$GH_TOKEN@$GH_REF"
>>>>>>> 07994ae532bb46ecc1d3ce9109a5716e5c82c42c

branches:
  only:
    - dev
env:
 global:
   - GH_REF: github.com/oopstorm/oopstorm.github.io